
const db = require('./database');

const images = {
  // Garlic Bread
  "Cheese Garlic Bread":             "https://loremflickr.com/400/300/cheese,garlic,bread",
  "Veg Cheese Garlic Bread":         "https://loremflickr.com/400/300/vegetable,cheese,garlic,bread",
  "Paneer Minced Garlic Bread":      "https://loremflickr.com/400/300/paneer,garlic,bread",
  "Mushroom Minced Garlic Bread":    "https://loremflickr.com/400/300/mushroom,garlic,bread",
  "Chicken Cheese Garlic Bread":     "https://loremflickr.com/400/300/chicken,cheese,garlic,bread",
  "Sausage Cheese Garlic Bread":     "https://loremflickr.com/400/300/sausage,cheese,bread",
  "Creamy Chicken Garlic Bread":     "https://loremflickr.com/400/300/creamy,chicken,garlic,bread",
  // Chicken Wings
  "Spicy Wings (Dry)":               "https://loremflickr.com/400/300/spicy,chicken,wings",
  "Honey BBQ Wings":                 "https://loremflickr.com/400/300/honey,bbq,chicken,wings",
  "Thai Sweet Chilli Wings":         "https://loremflickr.com/400/300/thai,chilli,chicken,wings",
  "Butter Garlic Wings":             "https://loremflickr.com/400/300/butter,garlic,chicken,wings",
  "Sweet and Spicy Wings":           "https://loremflickr.com/400/300/sweet,spicy,chicken,wings",
  "Buffalo Wings":                   "https://loremflickr.com/400/300/buffalo,chicken,wings",
  "Crispy Wings":                    "https://loremflickr.com/400/300/crispy,chicken,wings",
  "BBQ Wings (Signature)":           "https://loremflickr.com/400/300/bbq,chicken,wings",
  "Peri Peri Wings (Sauce)":         "https://loremflickr.com/400/300/peri,peri,chicken,wings",
  // Momos
  "Mix Veg Momos":                   "https://loremflickr.com/400/300/vegetable,dumplings,momos",
  "Paneer Momos":                    "https://loremflickr.com/400/300/paneer,dumplings",
  "Peri Peri Veg Momos":             "https://loremflickr.com/400/300/spicy,vegetable,dumplings",
  "Choco Loaded Veg Momos":          "https://loremflickr.com/400/300/cheese,vegetable,dumplings",
  "Manchurian Veg Momos":            "https://loremflickr.com/400/300/manchurian,dumplings",
  "Butter Garlic Veg Momos":         "https://loremflickr.com/400/300/butter,garlic,dumplings",
  "Chilli Veg Momos":                "https://loremflickr.com/400/300/chilli,dumplings",
  "Chicken Momos":                   "https://loremflickr.com/400/300/chicken,dumplings,momos",
  "Chicken Peri Peri Momos":         "https://loremflickr.com/400/300/spicy,chicken,dumplings",
  "Chicken Schezwan Momos":          "https://loremflickr.com/400/300/schezwan,chicken,dumplings",
  "Chicken Cheese Filling Momos":    "https://loremflickr.com/400/300/cheese,chicken,dumplings",
  "Manchurian Chicken Momos":        "https://loremflickr.com/400/300/manchurian,chicken,dumplings",
  "Butter Garlic Chicken Momos":     "https://loremflickr.com/400/300/butter,garlic,chicken,dumplings",
  "Chilli Chicken Momos":            "https://loremflickr.com/400/300/chilli,chicken,dumplings",
  // Starters
  "Aloo Tikki (5pcs)":               "https://loremflickr.com/400/300/aloo,tikki,potato,patty",
  "Chilli Garlic Potato Shots (20pc)":"https://loremflickr.com/400/300/chilli,garlic,potato",
  "Crispy Corn Bowl":                "https://loremflickr.com/400/300/crispy,corn",
  "Steamed Corn Bowl":               "https://loremflickr.com/400/300/steamed,corn",
  "Mushroom Pops":                   "https://loremflickr.com/400/300/mushroom,fried,snack",
  "Babycorn Fry":                    "https://loremflickr.com/400/300/babycorn,fried",
  "Nonsense Aloo":                   "https://loremflickr.com/400/300/spicy,potato,snack",
  "Crispy Paneer (8pc)":             "https://loremflickr.com/400/300/crispy,paneer",
  "Broasted Chicken (1pc)":          "https://loremflickr.com/400/300/broasted,chicken,fried",
  "Thai Sweet Broasted Chicken":     "https://loremflickr.com/400/300/thai,sweet,fried,chicken",
  "Chicken Meatballs (6pc)":         "https://loremflickr.com/400/300/chicken,meatballs",
  "Peri Peri Sausage":               "https://loremflickr.com/400/300/spicy,sausage",
  "BBQ Sausages":                    "https://loremflickr.com/400/300/bbq,sausage,grilled",
  "Sausage Gold Coins":              "https://loremflickr.com/400/300/sausage,sliced,fried",
  "Chicken Nuggets (8pcs)":          "https://loremflickr.com/400/300/chicken,nuggets",
  "Chicken Pops":                    "https://loremflickr.com/400/300/chicken,pops,crispy",
  "Crispy Chicken Fillets (8pcs)":   "https://loremflickr.com/400/300/crispy,chicken,fillets",
  "Thai Fried Chicken (8pcs)":       "https://loremflickr.com/400/300/thai,fried,chicken",
  "Thai Sweet Chilli Pops":          "https://loremflickr.com/400/300/thai,sweet,chilli,chicken",
  "Chicken Lollipop (5pcs)":         "https://loremflickr.com/400/300/chicken,lollipop",
  "Chicken Lollipop (8pcs)":         "https://loremflickr.com/400/300/chicken,lollipop,spicy",
  "Gobi Manchurian (Dry)":           "https://loremflickr.com/400/300/gobi,manchurian,cauliflower",
  "Gobi Manchurian (Gravy)":         "https://loremflickr.com/400/300/cauliflower,manchurian,gravy",
  "Mushroom Butter Garlic":          "https://loremflickr.com/400/300/mushroom,butter,garlic",
  "Babycorn Manchurian":             "https://loremflickr.com/400/300/babycorn,manchurian",
  "Paneer Butter Garlic":            "https://loremflickr.com/400/300/paneer,butter,garlic",
  "Chicken Manchurian":              "https://loremflickr.com/400/300/chicken,manchurian",
  "Chicken Manchurian (Gravy)":      "https://loremflickr.com/400/300/chicken,manchurian,gravy",
  "Hunan Chicken":                   "https://loremflickr.com/400/300/hunan,chicken",
  "Singaporean Chicken":             "https://loremflickr.com/400/300/singaporean,chicken,gravy",
  "Shanghai Chicken":                "https://loremflickr.com/400/300/shanghai,chicken,chinese",
  "Crispy Chicken Starter":          "https://loremflickr.com/400/300/crispy,chicken,gravy",
  "Bean Pepper Chicken":             "https://loremflickr.com/400/300/pepper,chicken,beans",
  "Drums of Heaven (6pcs)":          "https://loremflickr.com/400/300/drums,heaven,chicken,lollipop",
  "Chicken Fry Masala (5pcs)":       "https://loremflickr.com/400/300/chicken,fry,masala,spicy",
  // Soups
  "Tomato Soup":                     "https://loremflickr.com/400/300/tomato,soup",
  "Clear Soup":                      "https://loremflickr.com/400/300/clear,broth,soup",
  "Manchow Soup":                    "https://loremflickr.com/400/300/manchow,soup,noodles",
  "Hot and Sour Soup":               "https://loremflickr.com/400/300/hot,sour,soup",
  "Sweet Corn Soup":                 "https://loremflickr.com/400/300/sweet,corn,soup",
  "Thai Soup":                       "https://loremflickr.com/400/300/thai,soup,coconut",
  "Lung Fung Soup":                  "https://loremflickr.com/400/300/chinese,vegetable,soup",
  "Tom Yum Soup":                    "https://loremflickr.com/400/300/tom,yum,soup",
  // Salads
  "Veg Salad":                       "https://loremflickr.com/400/300/vegetable,salad,fresh",
  "Beat the Heat Salad":             "https://loremflickr.com/400/300/fresh,salad,cooling",
  "Egg Salad":                       "https://loremflickr.com/400/300/egg,salad",
  "Chicken Caesar Salad":            "https://loremflickr.com/400/300/chicken,caesar,salad",
  "Loaded Salad":                    "https://loremflickr.com/400/300/loaded,salad,chicken",
  // Nachos
  "Nachos with Dip":                 "https://loremflickr.com/400/300/nachos,dip,salsa",
  "Veg Loaded Cheese Nachos":        "https://loremflickr.com/400/300/nachos,cheese,vegetable",
  "Paneer Loaded Nachos":            "https://loremflickr.com/400/300/nachos,paneer,cheese",
  "Mushroom Loaded Nachos":          "https://loremflickr.com/400/300/nachos,mushroom,cheese",
  "Chicken Loaded Nachos":           "https://loremflickr.com/400/300/nachos,chicken,cheese",
  "Sausage Loaded Nachos":           "https://loremflickr.com/400/300/nachos,sausage,loaded",
  "Crispy Chicken Loaded Nachos":    "https://loremflickr.com/400/300/nachos,crispy,chicken",
  "Creamy Chicken Loaded Nachos":    "https://loremflickr.com/400/300/nachos,creamy,chicken",
  // Fries
  "Salted Fries":                    "https://loremflickr.com/400/300/french,fries,salted",
  "Peri Peri Fries":                 "https://loremflickr.com/400/300/peri,peri,fries,spicy",
  "BBQ Fries":                       "https://loremflickr.com/400/300/bbq,fries",
  "Cheese Fries":                    "https://loremflickr.com/400/300/cheese,fries",
  "Cheese Loaded Fries":             "https://loremflickr.com/400/300/loaded,cheese,fries",
  "Paneer Loaded Fries":             "https://loremflickr.com/400/300/paneer,loaded,fries",
  "Mushroom Loaded Fries":           "https://loremflickr.com/400/300/mushroom,loaded,fries",
  "Veg Salsa Style Fries":           "https://loremflickr.com/400/300/salsa,fries,vegetable",
  "Chicken Loaded Fries":            "https://loremflickr.com/400/300/chicken,loaded,fries",
  "Sausage Loaded Fries":            "https://loremflickr.com/400/300/sausage,loaded,fries",
  "Crispy Chicken Loaded Fries":     "https://loremflickr.com/400/300/crispy,chicken,fries",
  "Creamy Chicken Loaded Fries":     "https://loremflickr.com/400/300/creamy,chicken,fries",
  "Chicken Salsa Style Fries":       "https://loremflickr.com/400/300/chicken,salsa,fries",
  // Squid
  "Squid Fry":                       "https://loremflickr.com/400/300/squid,fried,seafood",
  "Squid Butter Garlic":             "https://loremflickr.com/400/300/squid,butter,garlic,seafood",
  "Squid Chilli":                    "https://loremflickr.com/400/300/squid,chilli,spicy",
  "Squid Pepper":                    "https://loremflickr.com/400/300/squid,pepper,seafood",
  "Squid Manchurian":                "https://loremflickr.com/400/300/squid,manchurian",
  "Squid Garlic":                    "https://loremflickr.com/400/300/squid,garlic,seafood",
  "Squid Ginger":                    "https://loremflickr.com/400/300/squid,ginger,seafood",
  "Squid Salt and Pepper":           "https://loremflickr.com/400/300/squid,salt,pepper",
  "Squid White Sauce":               "https://loremflickr.com/400/300/squid,white,sauce,seafood",
  "Squid Noodles":                   "https://loremflickr.com/400/300/squid,noodles",
  "Squid Fried Rice":                "https://loremflickr.com/400/300/squid,fried,rice",
  // Pizza
  "Margherita Pizza":                "https://loremflickr.com/400/300/margherita,pizza",
  "Veg Pizza":                       "https://loremflickr.com/400/300/vegetable,pizza",
  "Paneer Pizza":                    "https://loremflickr.com/400/300/paneer,pizza,indian",
  "Mushroom Pizza":                  "https://loremflickr.com/400/300/mushroom,pizza",
  "Corn Pizza":                      "https://loremflickr.com/400/300/corn,pizza",
  "Chicken Pizza":                   "https://loremflickr.com/400/300/chicken,pizza",
  "Chicken Salami Pizza":            "https://loremflickr.com/400/300/salami,pizza",
  "Crispy Chicken Pizza":            "https://loremflickr.com/400/300/crispy,chicken,pizza",
  "Fried Chicken Pizza":             "https://loremflickr.com/400/300/fried,chicken,pizza",
  "Peri Peri Chicken Pizza":         "https://loremflickr.com/400/300/spicy,chicken,pizza",
  "Chicken Sausage Pizza":           "https://loremflickr.com/400/300/sausage,pizza",
  "Chicken Ghee Roast Pizza":        "https://loremflickr.com/400/300/ghee,roast,chicken,pizza",
  "CC Special Pizza":                "https://loremflickr.com/400/300/special,pizza,loaded",
  "Chicken Chizza":                  "https://loremflickr.com/400/300/chicken,chizza,pizza",
  // Rolls
  "Veg Roll":                        "https://loremflickr.com/400/300/vegetable,roll,wrap",
  "Mushroom Roll":                   "https://loremflickr.com/400/300/mushroom,roll,wrap",
  "Paneer Roll":                     "https://loremflickr.com/400/300/paneer,roll,wrap",
  "Egg Roll":                        "https://loremflickr.com/400/300/egg,roll,wrap",
  "Chicken Roll":                    "https://loremflickr.com/400/300/chicken,roll,wrap",
  "Salami Roll":                     "https://loremflickr.com/400/300/salami,roll,wrap",
  "Crispy Chicken Roll":             "https://loremflickr.com/400/300/crispy,chicken,roll",
  "Chicken Nugget Roll":             "https://loremflickr.com/400/300/chicken,nugget,roll",
  "Creamy Chicken Roll":             "https://loremflickr.com/400/300/creamy,chicken,wrap",
  "Chicken Sausage Roll":            "https://loremflickr.com/400/300/sausage,chicken,roll",
  "Chicken Patty Roll":              "https://loremflickr.com/400/300/chicken,patty,roll",
  "Thai Sweet Chilli Chicken Roll":  "https://loremflickr.com/400/300/thai,chicken,wrap,roll",
  "Chicken Meatball Roll":           "https://loremflickr.com/400/300/meatball,chicken,roll",
  "Chicken Ghee Roast Roll":         "https://loremflickr.com/400/300/ghee,roast,chicken,roll",
  "CC Special Roll":                 "https://loremflickr.com/400/300/special,chicken,loaded,wrap",
  // Burgers
  "Aloo Tikki Burger":               "https://loremflickr.com/400/300/aloo,tikki,burger",
  "Double Cheese Veg Burger":        "https://loremflickr.com/400/300/double,cheese,veggie,burger",
  "Double Patty Veg Burger":         "https://loremflickr.com/400/300/double,patty,veg,burger",
  "Peri Peri Veg Burger":            "https://loremflickr.com/400/300/spicy,veg,burger",
  "Crispy Mushroom Burger":          "https://loremflickr.com/400/300/mushroom,burger,crispy",
  "BabyCorn Burger":                 "https://loremflickr.com/400/300/corn,veggie,burger",
  "Crispy Paneer Burger":            "https://loremflickr.com/400/300/paneer,burger,crispy",
  "No Bun Burger":                   "https://loremflickr.com/400/300/bunless,burger,lettuce,wrap",
  "Patty Chicken Burger":            "https://loremflickr.com/400/300/chicken,patty,burger",
  "Peri Peri Patty Burger":          "https://loremflickr.com/400/300/spicy,chicken,burger",
  "Double Patty Burger":             "https://loremflickr.com/400/300/double,patty,chicken,burger",
  "Double Cheese Burger":            "https://loremflickr.com/400/300/double,cheese,chicken,burger",
  "Crispy Chicken Burger":           "https://loremflickr.com/400/300/crispy,chicken,burger",
  "Peri Peri Crispy Burger":         "https://loremflickr.com/400/300/peri,peri,crispy,burger",
  "Double Crispy Burger":            "https://loremflickr.com/400/300/double,crispy,chicken,burger",
  "Creamy Chicken Burger":           "https://loremflickr.com/400/300/creamy,chicken,burger",
  "Chicken Nuggets Burger":          "https://loremflickr.com/400/300/nugget,chicken,burger",
  "Chicken Meatball Burger":         "https://loremflickr.com/400/300/meatball,burger",
  "Chicken Sausage Burger":          "https://loremflickr.com/400/300/sausage,chicken,burger",
  "Chicken Ghee Roast Burger":       "https://loremflickr.com/400/300/ghee,roast,chicken,burger",
  "Squid Burger":                    "https://loremflickr.com/400/300/squid,seafood,burger",
  "CC Special Burger":               "https://loremflickr.com/400/300/special,loaded,burger",
  // Maggi
  "Plain Maggi":                     "https://loremflickr.com/400/300/maggi,noodles,plain",
  "Veggies Maggi":                   "https://loremflickr.com/400/300/vegetable,noodles,maggi",
  "Soupy Maggi":                     "https://loremflickr.com/400/300/soupy,noodles,broth",
  "Spicy Maggi":                     "https://loremflickr.com/400/300/spicy,noodles,maggi",
  "Spicy Soupy Maggi":               "https://loremflickr.com/400/300/spicy,soup,noodles",
  "Milk Maggi":                      "https://loremflickr.com/400/300/milk,noodles,creamy",
  "Spicy Milk Maggi":                "https://loremflickr.com/400/300/spicy,creamy,noodles",
  "Soupy Momo Maggi (Veg)":          "https://loremflickr.com/400/300/dumpling,noodles,soup",
  "Egg Maggi":                       "https://loremflickr.com/400/300/egg,noodles,maggi",
  "Chicken Maggi":                   "https://loremflickr.com/400/300/chicken,noodles,maggi",
  "Sausage Maggi":                   "https://loremflickr.com/400/300/sausage,noodles",
  "Meatball Maggi":                  "https://loremflickr.com/400/300/meatball,noodles",
  "Soupy Momo Maggi (Non Veg)":      "https://loremflickr.com/400/300/chicken,dumpling,noodles,soup",
  // Egg
  "Half Fried Egg":                  "https://loremflickr.com/400/300/fried,egg,sunny,side",
  "Omelette":                        "https://loremflickr.com/400/300/omelette,egg",
  "Veggie Loaded Omelette":          "https://loremflickr.com/400/300/vegetable,omelette,loaded",
  "Peri Peri Omelette":              "https://loremflickr.com/400/300/spicy,omelette,egg",
  "Chicken Omelette":                "https://loremflickr.com/400/300/chicken,omelette",
  "Sausage Omelette":                "https://loremflickr.com/400/300/sausage,omelette",
  "Scrambled Egg":                   "https://loremflickr.com/400/300/scrambled,egg",
  "Egg Burji":                       "https://loremflickr.com/400/300/egg,bhurji,spicy,scrambled",
  "Cheese Omelette":                 "https://loremflickr.com/400/300/cheese,omelette",
  "Bread Omelette":                  "https://loremflickr.com/400/300/bread,omelette,egg",
  "Butter Omelette":                 "https://loremflickr.com/400/300/butter,omelette,egg",
  "Butter Bread Omelette":           "https://loremflickr.com/400/300/butter,bread,egg,omelette",
  "Creamy Cheese Omelette":          "https://loremflickr.com/400/300/creamy,cheese,omelette",
  "Egg Foo Young — Manchurian":      "https://loremflickr.com/400/300/egg,foo,young,chinese",
  "Egg Foo Young — Pepper":          "https://loremflickr.com/400/300/egg,foo,young,pepper",
  "Egg Foo Young — Garlic":          "https://loremflickr.com/400/300/egg,foo,young,garlic",
  "Egg Foo Young — Ginger":          "https://loremflickr.com/400/300/egg,foo,young,ginger",
  "Egg Foo Young — Butter Garlic":   "https://loremflickr.com/400/300/egg,foo,young,butter",
  // Sandwich
  "Plain Cheese Sandwich":           "https://loremflickr.com/400/300/cheese,sandwich,toasted",
  "Veg Sandwich":                    "https://loremflickr.com/400/300/vegetable,sandwich",
  "Peanut Butter Jelly Sandwich":    "https://loremflickr.com/400/300/peanut,butter,jelly,sandwich",
  "Nutella Sandwich":                "https://loremflickr.com/400/300/nutella,sandwich,chocolate",
  "Fries Sandwich":                  "https://loremflickr.com/400/300/fries,sandwich",
  "Corn Sandwich":                   "https://loremflickr.com/400/300/corn,sandwich",
  "Potato Sandwich":                 "https://loremflickr.com/400/300/potato,sandwich",
  "Paneer Sandwich":                 "https://loremflickr.com/400/300/paneer,sandwich,grilled",
  "Mushroom Sandwich":               "https://loremflickr.com/400/300/mushroom,sandwich",
  "Egg Sandwich":                    "https://loremflickr.com/400/300/egg,sandwich",
  "Chicken Sandwich":                "https://loremflickr.com/400/300/chicken,sandwich",
  "Crispy Chicken Sandwich":         "https://loremflickr.com/400/300/crispy,chicken,sandwich",
  "Chicken Patty Sandwich":          "https://loremflickr.com/400/300/chicken,patty,sandwich",
  "Creamy Chicken Sandwich":         "https://loremflickr.com/400/300/creamy,chicken,sandwich",
  "Meatball Sandwich":               "https://loremflickr.com/400/300/meatball,sandwich,sub",
  "Salami Sandwich":                 "https://loremflickr.com/400/300/salami,sandwich",
  "Nugget Sandwich":                 "https://loremflickr.com/400/300/nugget,chicken,sandwich",
  "Sausage Sandwich":                "https://loremflickr.com/400/300/sausage,sandwich",
  "Chicken Meatball Sandwich":       "https://loremflickr.com/400/300/chicken,meatball,sandwich",
  "Ghee Chicken Sandwich":           "https://loremflickr.com/400/300/ghee,roast,chicken,sandwich",
  "Double Decker Sandwich":          "https://loremflickr.com/400/300/double,decker,club,sandwich",
  "Pizza Sandwich":                  "https://loremflickr.com/400/300/pizza,sandwich,loaded",
  "CC Special Sandwich":             "https://loremflickr.com/400/300/special,loaded,chicken,sandwich",
  // Breakfast
  "Evening Breakfast":               "https://loremflickr.com/400/300/breakfast,toast,egg,sausage",
  "All Day Breakfast":               "https://loremflickr.com/400/300/full,english,breakfast,plate",
  // Mojito
  "Virgin Mojito":                   "https://loremflickr.com/400/300/virgin,mojito,mint,lime",
  "Green Mint Mojito":               "https://loremflickr.com/400/300/mint,mojito,green",
  "Watermelon Mojito":               "https://loremflickr.com/400/300/watermelon,mojito,drink",
  "Kiwi Mojito":                     "https://loremflickr.com/400/300/kiwi,mojito,drink",
  "Green Apple Mojito":              "https://loremflickr.com/400/300/green,apple,mojito",
  "Blueberry Mojito":                "https://loremflickr.com/400/300/blueberry,mojito,drink",
  "Guava Chilli Mojito":             "https://loremflickr.com/400/300/guava,chilli,drink",
  "Strawberry Mojito":               "https://loremflickr.com/400/300/strawberry,mojito,drink",
  "Pineapple Mojito":                "https://loremflickr.com/400/300/pineapple,mojito,tropical",
  "Black Currant Mojito":            "https://loremflickr.com/400/300/blackcurrant,mojito,purple",
  "Spicy Mojito":                    "https://loremflickr.com/400/300/spicy,mojito,chilli,drink",
  "Blue Curacao Mojito":             "https://loremflickr.com/400/300/blue,curacao,mojito,drink",
  "Mango Mojito":                    "https://loremflickr.com/400/300/mango,mojito,tropical",
  "Passion Fruit Mojito":            "https://loremflickr.com/400/300/passion,fruit,mojito",
  "Cranberry Mojito":                "https://loremflickr.com/400/300/cranberry,mojito,red",
  // Milkshakes
  "Chocolate Milkshake":             "https://loremflickr.com/400/300/chocolate,milkshake",
  "Strawberry Milkshake":            "https://loremflickr.com/400/300/strawberry,milkshake",
  "Vanilla Milkshake":               "https://loremflickr.com/400/300/vanilla,milkshake",
  "Butterscotch Milkshake":          "https://loremflickr.com/400/300/butterscotch,milkshake",
  "Cold Coffee Milkshake":           "https://loremflickr.com/400/300/cold,coffee,milkshake",
  "Blackcurrant Milkshake":          "https://loremflickr.com/400/300/blackcurrant,milkshake,purple",
  "Badami Milkshake":                "https://loremflickr.com/400/300/almond,milkshake",
  "Boost / Horlicks Milkshake":      "https://loremflickr.com/400/300/energy,malt,milkshake",
  "Bournvita Milkshake":             "https://loremflickr.com/400/300/chocolate,malt,milkshake",
  "Oreo Milkshake":                  "https://loremflickr.com/400/300/oreo,milkshake,cookies",
  "Peanut Butter Milkshake":         "https://loremflickr.com/400/300/peanut,butter,milkshake",
  "Banana Milkshake":                "https://loremflickr.com/400/300/banana,milkshake",
  "Spl Berry Milkshake":             "https://loremflickr.com/400/300/berry,milkshake,mix",
  "Nutella Milkshake":               "https://loremflickr.com/400/300/nutella,milkshake,hazelnut",
  "Choco Peanut Butter Milkshake":   "https://loremflickr.com/400/300/chocolate,peanut,butter,milkshake",
  "Mango Milkshake":                 "https://loremflickr.com/400/300/mango,milkshake,tropical",
  "Mango Strawberry Milkshake":      "https://loremflickr.com/400/300/mango,strawberry,milkshake",
  "Blueberry Milkshake":             "https://loremflickr.com/400/300/blueberry,milkshake",
  "Peanut Butter Nutella Milkshake": "https://loremflickr.com/400/300/peanut,nutella,milkshake",
  "Bubblegum Milkshake":             "https://loremflickr.com/400/300/bubblegum,pink,milkshake",
  "Banana Peanut Butter Milkshake":  "https://loremflickr.com/400/300/banana,peanut,butter,milkshake",
  "Strawberry Oreo Milkshake":       "https://loremflickr.com/400/300/strawberry,oreo,milkshake",
  "Chocolate Oreo Milkshake":        "https://loremflickr.com/400/300/chocolate,oreo,milkshake",
  // Fruit Juice
  "Orange is the New Black Juice":   "https://loremflickr.com/400/300/orange,juice,fresh",
  "Mr Melon Juice":                  "https://loremflickr.com/400/300/melon,juice,fresh",
  "Elon Muskmelon Juice":            "https://loremflickr.com/400/300/muskmelon,juice",
  "Pineapple Express Juice":         "https://loremflickr.com/400/300/pineapple,juice,fresh",
  "Adams Apple Juice":               "https://loremflickr.com/400/300/apple,juice,fresh",
  // Iced Tea
  "Lime Iced Tea":                   "https://loremflickr.com/400/300/lime,iced,tea",
  "Peach Iced Tea":                  "https://loremflickr.com/400/300/peach,iced,tea",
  "Watermelon Iced Tea":             "https://loremflickr.com/400/300/watermelon,iced,tea",
  "Cranberry Iced Tea":              "https://loremflickr.com/400/300/cranberry,iced,tea",
  "Kiwi Iced Tea":                   "https://loremflickr.com/400/300/kiwi,iced,tea",
  "Iced Americano":                  "https://loremflickr.com/400/300/iced,americano,cold,coffee",
  // Dessert
  "Fruit Salad":                     "https://loremflickr.com/400/300/fruit,salad,fresh",
  "Fruit Salad with Icecream":       "https://loremflickr.com/400/300/fruit,salad,ice,cream",
  "Brownie with Icecream":           "https://loremflickr.com/400/300/brownie,ice,cream,dessert",
  "Vanilla Icecream":                "https://loremflickr.com/400/300/vanilla,ice,cream,scoop",
  "Midnight Oreo Crunch":            "https://loremflickr.com/400/300/oreo,chocolate,ice,cream",
  // Beverages
  "Joy Cola / Orange":               "https://loremflickr.com/400/300/cola,soft,drink,bottle",
  "Zaffa Lime":                      "https://loremflickr.com/400/300/lime,soda,drink,bottle",
  "Pepsi":                           "https://loremflickr.com/400/300/pepsi,cola,drink",
  "Mountain Dew":                    "https://loremflickr.com/400/300/mountain,dew,green,drink",
};

let updated = 0, notFound = 0;

const entries = Object.entries(images);
let i = 0;

function next() {
  if (i >= entries.length) {
    console.log(`\n✅ Done! ${updated} updated, ${notFound} not found in DB.`);
    db.close();
    return;
  }
  const [name, url] = entries[i++];
  db.run('UPDATE menu SET image_url=? WHERE name=?', [url, name], function(err) {
    if (err) { console.error('Error:', name, err.message); }
    else if (this.changes === 0) { notFound++; console.log('Not found:', name); }
    else { updated++; process.stdout.write('.'); }
    next();
  });
}

next();
